### ISSUE TITLE
StopDevice() Add RemapImage.reset()

### ISSUE THREAD

**Issue by YongsunLee** [nama-gatsuo/AzureKinectForUE#2]
Hi, @nama-gatsuo 

When I use this plugin
I think that StopDevice() should contain the following contents.

![image](https://user-images.githubusercontent.com/21377584/140720707-6831ff3c-cfa9-4f82-92b9-653be8a33490.png)

This is because if you change the Remap Mode after executing it once and exiting, the previous RemapImage data remains and is not applied.

**Comment by nama-gatsuo** [comment]
HI @YongsunLee ,

Thanks again for reporting. You are right. Just added lines you provided above and committed to master.
